### ISSUE TITLE
Distorted images and CORS issues

### ISSUE THREAD

**Issue by rcobiella** [FrankFlitton/vue-2-img#1]
Hi there! I'm not sure if this is still being maintained, but in case it is, I've found a couple issues you might be able to help with.

For some reason, the images inside the element I'm trying to export (to any format) all appear distorted in the resulting file. Not just blurry, but also somehow elongated, and with a different aspect ratio. Is there a known workaround for this?

The other problem happened with CORS (tainted canvas cannot be exported), but I was able to fix adding `crossOrigin: "anonymous"` after each `new Image()`, which seems to be working. 

Thank you!

**Comment by FrankFlitton** [comment]
Thanks for sharing this. as far as your specific issues:

1. Image distortion:
I haven't encountered this, personally. Is the image set as a background image with css or with a <img> or <picture> element?

2. CORS:
Thanks for the fix! I can incorporate it into the codebase.

Can you share some example code to reproduce you issue? 

I'll release an (overdue) update once we can settle these issues.

**Comment by FrankFlitton** [comment]
I encountered the image distortion when applying the CORS anonymous fix. It should be patched now, let me know if it's working for you. Version `0.0.5` is live on npm.  https://www.npmjs.com/package/vue-2-img

**Comment by rcobiella** [comment]
Thank you for the quick action!

Unfortunately I get this error now as soon as I execute the function, both using imports and the CDN 

<img width="900" alt="vue2img" src="https://user-images.githubusercontent.com/25663413/99697339-f429c480-2a8f-11eb-8a5c-4ac70c73732c.png">

**Comment by rcobiella** [comment]
Hi again,

I took a moment to look at this, and got it to run by changing this:
`document.querySelectorAll(target + ' img').forEach(function (imageNode, index) {`

to this:
`document.querySelectorAll('img').forEach(function (imageNode, index) {`

Probably not the best performance though, but I just wanted to find a quick fix to see if it worked. Maybe `target.querySelectorAll('img').forEach...` is the right way?

Now that I got it to work I jumped into more problems though! Not in your code, but with html2canvas not rendering `mix-blend-mode`, and sizing images with `object-fit` incorrectly :\. There's been plenty of issues opened throughout the years with workarounds to implement it in case you're interested in adding them!

object-fit: [https://github.com/niklasvh/html2canvas/issues/725
](url)
mix-blend-mode: [https://github.com/niklasvh/html2canvas/issues/580](url) + [https://codepen.io/SevKel/pen/ZEOLPEg](url)

**Comment by FrankFlitton** [comment]
Thanks for checking that out and recommending a fix. I implemented the `target` container node then find `img` elements in the child nodes.

Yeah, html2canvas is great when it works. It's been sluggish to support some of the new HTML/CSS features. I've thought of maintaining a fork with some fixes/additions, depends on how large the scope of the project will get.

**Comment by FrankFlitton** [comment]
0.0.6 is live now with the fix. I'll close the issue. Thanks again.
